### ISSUE TITLE
up有交流群吗， 前端npm i报错

### ISSUE THREAD

**Issue by byXewl** [zhouhw0306/forum-bs#2]
![image](https://github.com/user-attachments/assets/a0854ab1-edc1-4092-a5e8-b30eec2d129b)
前端npm i报错，python2 node14环境

**Comment by zhouhw0306** [comment]
单独执行npm i node-sass@4.14.1试试

**Comment by byXewl** [comment]
npm i node-sass@4.14.1
npm WARN deprecated node-sass@4.14.1: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.
npm WARN deprecated npmlog@4.1.2: This package is no longer supported.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142  
npm WARN deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
npm WARN deprecated fstream@1.0.12: This package is no longer supported.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated osenv@0.1.5: This package is no longer supported.
npm WARN deprecated gauge@2.7.4: This package is no longer supported.
npm WARN deprecated are-we-there-yet@1.1.7: This package is no longer supported.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random   for details.

> node-sass@4.14.1 install E:\Users\Administrator.DESKTOP-L9N4RF9\Desktop\FinalDesign\shequ\forum-bs\forum-client\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://npm.taobao.org/mirrors/node-sass/v4.14.1/win32-x64-83_binding.node  
Cannot download "https://npm.taobao.org/mirrors/node-sass/v4.14.1/win32-x64-83_binding.node&#34;:  

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234  

or configure npm proxy via

      npm config set proxy http://example.com:8080  

> node-sass@4.14.1 postinstall E:\Users\Administrator.DESKTOP-L9N4RF9\Desktop\FinalDesign\shequ\forum-bs\forum-client\node_modules\node-sass
> node scripts/build.js

Building: E:\Program Files\nodejs\node.exe E:\Users\Administrator.DESKTOP-L9N4RF9\Desktop\FinalDesign\shequ\forum-bs\forum-client\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'E:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\Users\\Administrator.DESKTOP-L9N4RF9\\Desktop\\FinalDesign\\shequ\\forum-bs\\forum-client\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.20.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb download using dist-url https://npm.taobao.org/mirrors/node  
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 D:\mypython\Python27\python2.EXE
gyp verb check python version `D:\mypython\Python27\python2.EXE -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.20.0
gyp verb command install [ '14.20.0' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb download using dist-url https://npm.taobao.org/mirrors/node  
gyp verb install input version string "14.20.0"
gyp verb install installing version: 14.20.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 14.20.0
gyp verb ensuring nodedir is created C:\Users\Administrator.DESKTOP-L9N4RF9\.node-gyp\14.20.0
gyp verb created nodedir C:\Users\Administrator.DESKTOP-L9N4RF9\.node-gyp\14.20.0
gyp http GET https://npm.taobao.org/mirrors/node/v14.20.0/node-v14.20.0-headers.tar.gz  
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.20.0' ]
gyp verb remove using node-gyp dir: C:\Users\Administrator.DESKTOP-L9N4RF9\.node-gyp
gyp verb remove removing target version: 14.20.0
gyp verb remove removing development files for version: 14.20.0
gyp ERR! configure error
gyp ERR! stack Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: npm.taobao.org. is not in the cert's altnames: DNS:*.tbcdn.cn, DNS:*.taobao.com, DNS:*.alicdn.com, DNS:*.cmos.greencompute.org, DNS:cmos.greencompute.org, DNS:m.intl.taobao.com, DNS:*.mobgslb.tbcache.com, DNS:*.alikunlun.com, DNS:alikunlun.com, DNS:*.django.t.taobao.com, DNS:alicdn.com, DNS:*.tbcache.com, DNS:*.tmall.com, DNS:*.1688.com, DNS:*.3c.tmall.com, DNS:*.alibaba.com, DNS:*.aliexpress.com, DNS:*.aliqin.tmall.com, DNS:*.alitrip.com, DNS:*.aliyun.com, DNS:*.cainiao.com, DNS:*.cainiao.com.cn, DNS:*.chi.taobao.com, DNS:*.chi.tmall.com, DNS:*.china.taobao.com, DNS:*.dingtalk.com, DNS:*.etao.com, DNS:*.feizhu.cn, DNS:*.feizhu.com, DNS:*.fliggy.com, DNS:*.fliggy.hk, DNS:*.food.tmall.com, DNS:*.jia.taobao.com, DNS:*.jia.tmall.com, DNS:*.ju.taobao.com, DNS:*.juhuasuan.com, DNS:*.lw.aliimg.com, DNS:*.m.1688.com, DNS:*.m.alibaba.com, DNS:*.m.alitrip.com, DNS:*.m.cainiao.com, DNS:*.m.etao.com, DNS:*.m.taobao.com, DNS:*.m.taopiaopiao.com, DNS:*.m.tmall.com, DNS:*.m.tmall.hk, DNS:*.mei.com, DNS:*.taopiaopiao.com, DNS:*.tmall.hk, DNS:*.trip.taobao.com, DNS:*.xiami.com, DNS:1688.com, DNS:alibaba.com, DNS:aliexpress.com, DNS:alitrip.com, DNS:aliyun.com, DNS:cainiao.com, DNS:cainiao.com.cn, DNS:dingtalk.com, DNS:etao.com, DNS:feizhu.cn, DNS:feizhu.com, DNS:fliggy.com, DNS:fliggy.hk, DNS:juhuasuan.com, DNS:mei.com, DNS:taobao.com, DNS:taopiaopiao.com, DNS:tmall.hk, DNS:xiami.com, DNS:tmall.com, DNS:*.cloudvideocdn.taobao.com, DNS:cloudvideocdn.taobao.com, DNS:tbcdn.cn
gyp ERR! stack     at new NodeError (internal/errors.js:322:7)
gyp ERR! stack     at Object.checkServerIdentity (tls.js:347:12)
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1525:27)
gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:937:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Users\\Administrator.DESKTOP-L9N4RF9\\Desktop\\FinalDesign\\shequ\\forum-bs\\forum-client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\Users\Administrator.DESKTOP-L9N4RF9\Desktop\FinalDesign\shequ\forum-bs\forum-client\node_modules\node-sass
gyp ERR! node -v v14.20.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN sass-loader@8.0.0 requires a peer of webpack@^4.36.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator.DESKTOP-L9N4RF9\AppData\Roaming\npm-cache\_logs\2024-10-26T16_26_02_251Z-debug.log

E:\Users\Administrator.DESKTOP-L9N4RF9\Desktop\FinalDesign\shequ\forum-bs\forum-client>

**Comment by byXewl** [comment]
python2 node14
然后
npm install node-sass@^4.14.1 --registry=https://registry.npmmirror.com --sass_binary_site=https://www.npmmirror.com/mirrors/node-sass/

可以了
但是运行又
![image](https://github.com/user-attachments/assets/c380a448-f2ba-476a-8d9c-b9be94c8b814)
up的node版本是多少啊

**Comment by zhouhw0306** [comment]
> 正在从 https://npm.taobao.org/mirrors/node-sass/v4.14.1/win32-x64-83_binding.node 下载二进制文件无法下载 “https://npm.taobao.org/mirrors/node-sass/v4.14.1/win32-x64-83_binding.node&#34;：

我已经将node-sass改为使用dart-sass了，你可以pull最新的代码
